"""empty message

Revision ID: 3489d43bffe5
Revises: cb295d10052d
Create Date: 2021-06-25 23:33:17.387063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3489d43bffe5'
down_revision = 'cb295d10052d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('testing', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'testing')
    # ### end Alembic commands ###
