"""empty message

Revision ID: cb295d10052d
Revises: 651f653ae933
Create Date: 2021-06-25 23:18:57.764335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb295d10052d'
down_revision = '651f653ae933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'testing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('testing', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
